export * from '../../../core/weapp/init/data';
export * from '../../../core/weapp/init/computed';
export * from './lifecycle';
export * from './methods';
export * from '../../../core/weapp/init/watch';
export * from './props';
export * from '../../../core/weapp/init/mixins';
export * from '../../../core/weapp/init/hooks';
export * from '../../../core/weapp/init/relations';
