#!/usr/bin/expect -f

set dist [lindex $argv 0]

set timeout 30

spawn wepy init standard $dist

expect "Project name"
send "standard-project\n"

expect "AppId"
send "\n"

expect "Project description"
send "\n"

expect "Author"
send "\n"

expect "Use ESLint to lint your code"
send "y\n"

expect "Use Redux in your project"
send "y\n"

expect "Use web transform feature in your project"
send "y\n"

send_user  "\nStandard template generatedg\n"

interact
